[2022-09-21T22:23:40.411+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: postgres_operator_dag_example.export_pet_to_csv manual__2022-09-21T22:23:31.726194+00:00 [queued]>
[2022-09-21T22:23:40.417+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: postgres_operator_dag_example.export_pet_to_csv manual__2022-09-21T22:23:31.726194+00:00 [queued]>
[2022-09-21T22:23:40.418+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2022-09-21T22:23:40.419+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 2
[2022-09-21T22:23:40.420+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2022-09-21T22:23:40.428+0000] {taskinstance.py:1389} INFO - Executing <Task(PythonOperator): export_pet_to_csv> on 2022-09-21 22:23:31.726194+00:00
[2022-09-21T22:23:40.433+0000] {standard_task_runner.py:52} INFO - Started process 63182 to run task
[2022-09-21T22:23:40.436+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'postgres_operator_dag_example', 'export_pet_to_csv', 'manual__2022-09-21T22:23:31.726194+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/postgresql_demo.py', '--cfg-path', '/tmp/tmpvttxmzwz', '--error-file', '/tmp/tmpkwuj652w']
[2022-09-21T22:23:40.450+0000] {standard_task_runner.py:80} INFO - Job 19: Subtask export_pet_to_csv
[2022-09-21T22:23:40.499+0000] {task_command.py:371} INFO - Running <TaskInstance: postgres_operator_dag_example.export_pet_to_csv manual__2022-09-21T22:23:31.726194+00:00 [running]> on host 49fa11dd9034
[2022-09-21T22:23:40.544+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=jsanchez
AIRFLOW_CTX_DAG_ID=postgres_operator_dag_example
AIRFLOW_CTX_TASK_ID=export_pet_to_csv
AIRFLOW_CTX_EXECUTION_DATE=2022-09-21T22:23:31.726194+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-09-21T22:23:31.726194+00:00
[2022-09-21T22:23:40.552+0000] {base.py:68} INFO - Using connection ID 'qa_ai_external_db' for task execution.
[2022-09-21T22:23:40.693+0000] {postgresql_demo.py:17} INFO - Exporting query to file '/data/***_demo/pet.csv'
[2022-09-21T22:23:40.695+0000] {postgres.py:127} INFO - Running copy expert: COPY (SELECT * FROM ***_demo.pet) TO STDOUT WITH CSV HEADER DELIMITER ',', filename: /data/***_demo/pet.csv
[2022-09-21T22:23:40.730+0000] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/postgresql_demo.py", line 18, in export_to_csv
    pg_hook.copy_expert(copy_sql, filename=file_name)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 129, in copy_expert
    with open(filename, 'w'):
FileNotFoundError: [Errno 2] No such file or directory: '/data/airflow_demo/pet.csv'
[2022-09-21T22:23:40.741+0000] {taskinstance.py:1412} INFO - Marking task as UP_FOR_RETRY. dag_id=postgres_operator_dag_example, task_id=export_pet_to_csv, execution_date=20220921T222331, start_date=20220921T222340, end_date=20220921T222340
[2022-09-21T22:23:40.751+0000] {standard_task_runner.py:97} ERROR - Failed to execute job 19 for task export_pet_to_csv ([Errno 2] No such file or directory: '/data/airflow_demo/pet.csv'; 63182)
[2022-09-21T22:23:40.785+0000] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-09-21T22:23:40.814+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
