[2022-09-21T21:15:55.903+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: postgres_operator_dag_example.create_airflow_demo_schema scheduled__2022-09-21T00:00:00+00:00 [queued]>
[2022-09-21T21:15:55.914+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: postgres_operator_dag_example.create_airflow_demo_schema scheduled__2022-09-21T00:00:00+00:00 [queued]>
[2022-09-21T21:15:55.915+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2022-09-21T21:15:55.917+0000] {taskinstance.py:1369} INFO - Starting attempt 2 of 2
[2022-09-21T21:15:55.918+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2022-09-21T21:15:55.928+0000] {taskinstance.py:1389} INFO - Executing <Task(PostgresOperator): create_airflow_demo_schema> on 2022-09-21 00:00:00+00:00
[2022-09-21T21:15:55.941+0000] {standard_task_runner.py:52} INFO - Started process 59618 to run task
[2022-09-21T21:15:55.947+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'postgres_operator_dag_example', 'create_***_demo_schema', 'scheduled__2022-09-21T00:00:00+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/postgresql_demo.py', '--cfg-path', '/tmp/tmpvk__cepr', '--error-file', '/tmp/tmp345ewrk8']
[2022-09-21T21:15:55.953+0000] {standard_task_runner.py:80} INFO - Job 8: Subtask create_***_demo_schema
[2022-09-21T21:15:56.055+0000] {task_command.py:371} INFO - Running <TaskInstance: postgres_operator_dag_example.create_airflow_demo_schema scheduled__2022-09-21T00:00:00+00:00 [running]> on host 49fa11dd9034
[2022-09-21T21:15:56.152+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=postgres_operator_dag_example
AIRFLOW_CTX_TASK_ID=create_***_demo_schema
AIRFLOW_CTX_EXECUTION_DATE=2022-09-21T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-21T00:00:00+00:00
[2022-09-21T21:15:56.177+0000] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/operators/postgres.py", line 92, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 288, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 86, in get_conn
    conn = deepcopy(self.connection or self.get_connection(conn_id))
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 430, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_default` isn't defined
[2022-09-21T21:15:56.199+0000] {taskinstance.py:1412} INFO - Marking task as FAILED. dag_id=postgres_operator_dag_example, task_id=create_***_demo_schema, execution_date=20220921T000000, start_date=20220921T211555, end_date=20220921T211556
[2022-09-21T21:15:56.239+0000] {standard_task_runner.py:97} ERROR - Failed to execute job 8 for task create_***_demo_schema (The conn_id `postgres_default` isn't defined; 59618)
[2022-09-21T21:15:56.286+0000] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-09-21T21:15:56.319+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
