[2022-09-21T22:23:38.414+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: postgres_operator_dag_example.insert_pet_table manual__2022-09-21T22:23:31.726194+00:00 [queued]>
[2022-09-21T22:23:38.426+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: postgres_operator_dag_example.insert_pet_table manual__2022-09-21T22:23:31.726194+00:00 [queued]>
[2022-09-21T22:23:38.435+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2022-09-21T22:23:38.436+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 2
[2022-09-21T22:23:38.438+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2022-09-21T22:23:38.452+0000] {taskinstance.py:1389} INFO - Executing <Task(PostgresOperator): insert_pet_table> on 2022-09-21 22:23:31.726194+00:00
[2022-09-21T22:23:38.458+0000] {standard_task_runner.py:52} INFO - Started process 63178 to run task
[2022-09-21T22:23:38.461+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'postgres_operator_dag_example', 'insert_pet_table', 'manual__2022-09-21T22:23:31.726194+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/postgresql_demo.py', '--cfg-path', '/tmp/tmpleui1whe', '--error-file', '/tmp/tmphjt4kl0y']
[2022-09-21T22:23:38.467+0000] {standard_task_runner.py:80} INFO - Job 18: Subtask insert_pet_table
[2022-09-21T22:23:38.524+0000] {task_command.py:371} INFO - Running <TaskInstance: postgres_operator_dag_example.insert_pet_table manual__2022-09-21T22:23:31.726194+00:00 [running]> on host 49fa11dd9034
[2022-09-21T22:23:38.580+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=jsanchez
AIRFLOW_CTX_DAG_ID=postgres_operator_dag_example
AIRFLOW_CTX_TASK_ID=insert_pet_table
AIRFLOW_CTX_EXECUTION_DATE=2022-09-21T22:23:31.726194+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-09-21T22:23:31.726194+00:00
[2022-09-21T22:23:38.590+0000] {base.py:68} INFO - Using connection ID 'qa_ai_external_db' for task execution.
[2022-09-21T22:23:39.178+0000] {sql.py:315} INFO - Running statement: INSERT INTO ***_demo.pet (name, pet_type, birth_date, OWNER) VALUES ( 'Max', 'Dog', '2018-07-05', 'Jane');
            INSERT INTO ***_demo.pet (name, pet_type, birth_date, OWNER) VALUES ( 'Susie', 'Cat', '2019-05-01', 'Phil');
            INSERT INTO ***_demo.pet (name, pet_type, birth_date, OWNER) VALUES ( 'Lester', 'Hamster', '2020-06-23', 'Lily');
            INSERT INTO ***_demo.pet (name, pet_type, birth_date, OWNER) VALUES ( 'Quincy', 'Parrot', '2013-08-11', 'Anne'), parameters: None
[2022-09-21T22:23:39.386+0000] {sql.py:324} INFO - Rows affected: 1
[2022-09-21T22:23:39.497+0000] {taskinstance.py:1412} INFO - Marking task as SUCCESS. dag_id=postgres_operator_dag_example, task_id=insert_pet_table, execution_date=20220921T222331, start_date=20220921T222338, end_date=20220921T222339
[2022-09-21T22:23:39.578+0000] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-09-21T22:23:39.609+0000] {local_task_job.py:279} INFO - 1 downstream tasks scheduled from follow-on schedule check
